 <?php include dirname(dirname(dirname(__FILE__)))."/inc/banner.php"?>
   <div class="listpos fz13"><span class="gray">当前位置：</span><a href="/">首页</a> > <a href="<?php print  AppUrl::toll() ?>">价格与收费</a></div>
<?php include dirname(dirname(dirname(__FILE__)))."/modules/help/right.tpl.php"?>
  <div class="wid680 border2 fr">
      <div class="lcbox">
        <div class="lcboxtit tc fz24 blue">价格与收费</div>
        <div class="blank30"></div>
        <div class="jgsf">
		<table width="100%" cellspacing="0" cellpadding="0" border="0">
		  <tbody><tr>
			<td valign="middle" align="center" class="blank">编号</td>
			<td valign="middle" align="center" class="blank">项目名称</td>
			<td valign="middle" align="center" class="blank">规格</td>
			<td valign="middle" align="center" class="blank">收费标准</td>
		  </tr>
		  <tr>
			<td>001</td>
			<td>备皮</td>
			<td>/次</td>
			<td>30.00元</td>
		  </tr>
		  <tr>
			<td>002</td>
			<td>导尿</td>
			<td>/次</td>
			<td>50.00元</td>
		  </tr>
		  <tr>
			<td>003</td>
			<td>导尿护理</td>
			<td>/天</td>
			<td>10.00元</td>
		  </tr>
		  <tr>
			<td>004</td>
			<td>三级护理</td>
			<td>/天</td>
			<td>10.00元</td>
		  </tr>
		  <tr>
			<td>005</td>
			<td>二级护理</td>
			<td>/天</td>
			<td>20.00元</td>
		  </tr>
		  <tr>
			<td>006</td>
			<td>一级护理</td>
			<td>/天</td>
			<td>30.00元</td>
		  </tr>
		  <tr>
			<td>007</td>
			<td>褥疮护理</td>
			<td>/次</td>
			<td>50.00元</td>
		  </tr>
		  <tr>
			<td>008</td>
			<td>皮肤护理</td>
			<td>/次</td>
			<td>30.00元</td>
		  </tr>
		  <tr>
			<td>009</td>
			<td>心电监护仪</td>
			<td>/小时</td>
			<td>10.00元</td>
		  </tr>
		  <tr>
			<td>010</td>
			<td>置胃管术</td>
			<td>/次</td>
			<td>50.00元</td>
		  </tr>
		  <tr>
			<td>011</td>
			<td>气管切开插管</td>
			<td>/次</td>
			<td>150.00元</td>
		  </tr>
		  <tr>
			<td>012</td>
			<td>静脉切开</td>
			<td>/次</td>
			<td>100.00元</td>
		  </tr>
		  <tr>
			<td>013</td>
			<td>留置导尿</td>
			<td>/次</td>
			<td>50.00元</td>
		  </tr>
		  <tr>
			<td>014</td>
			<td>留置导尿护理</td>
			<td>/次</td>
			<td>5.00元</td>
		  </tr>
		  <tr>
			<td>015</td>
			<td>膀胱冲洗</td>
			<td>/次</td>
			<td>20.00元</td>
		  </tr>
		  <tr>
			<td>016</td>
			<td>肛管排气</td>
			<td>/次</td>
			<td>20.00元</td>
		  </tr>
		  <tr>
			<td>017</td>
			<td>洗胃</td>
			<td>/次</td>
			<td>100.00元</td>
		  </tr>
		  <tr>
			<td>018</td>
			<td>输液观察</td>
			<td>/次</td>
			<td>20.00元</td>
		  </tr>
		  <tr>
			<td>019</td>
			<td>静脉留置针穿刺</td>
			<td>/次</td>
			<td>20.00元</td>
		  </tr>
		  <tr>
			<td>020</td>
			<td>泛影普胺皮试</td>
			<td>/次</td>
			<td>16.00元</td>
		  </tr>
		  <tr>
			<td>021</td>
			<td>皮下注射</td>
			<td>/次</td>
			<td>5.00元</td>
		  </tr>
		  <tr>
			<td>022</td>
			<td>肌肉注射</td>
			<td>/次</td>
			<td>5.00元</td>
		  </tr>
		  <tr>
			<td>023</td>
			<td>静脉注射</td>
			<td>/次</td>
			<td>8.00元</td>
		  </tr>
		  <tr>
			<td>023</td>
			<td>静脉输液</td>
			<td>/次</td>
			<td>15.00元</td>
		  </tr>
		  <tr>
			<td>024</td>
			<td>心内注射</td>
			<td>/次</td>
			<td>20.00元</td>
		  </tr>
		  <tr>
			<td>025</td>
			<td>住院诊疗费</td>
			<td>/次</td>
			<td>20.00元</td>
		  </tr>
		  <tr>
			<td>026</td>
			<td>胸穿</td>
			<td>/次</td>
			<td>100.00元</td>
		  </tr>
		  <tr>
			<td>028</td>
			<td>腰穿</td>
			<td>/次</td>
			<td>100.00元</td>
		  </tr>
		  <tr>
			<td>029</td>
			<td>腹穿</td>
			<td>/次</td>
			<td>100.00元</td>
		  </tr>
		  <tr>
			<td>030</td>
			<td>护工费</td>
			<td>/次</td>
			<td>50.00元</td>
		  </tr>
		  <tr>
			<td>031</td>
			<td>病房床位费（卫）</td>
			<td>/次</td>
			<td>60.00元</td>
		  </tr>
		  <tr>
			<td>032</td>
			<td>病房床位费</td>
			<td>/次</td>
			<td>40.00元</td>
		  </tr>
		  <tr>
			<td>033</td>
			<td>住院留观费</td>
			<td>/次</td>
			<td>60.00元</td>
		  </tr>
		  <tr>
			<td>034</td>
			<td>血常规</td>
			<td>/次</td>
			<td>18.00元</td>
		  </tr>
		  <tr>
			<td>035</td>
			<td>凝血四项</td>
			<td>/次</td>
			<td>60.00元</td>
		  </tr>
		  <tr>
			<td>035</td>
			<td>尿微量白蛋白</td>
			<td>/次</td>
			<td>40.00元</td>
		  </tr>
		  <tr>
			<td>036</td>
			<td>尿常规10项</td>
			<td>/次</td>
			<td>10.00元</td>
		  </tr>
		  <tr>
			<td>037</td>
			<td>尿培养</td>
			<td>/次</td>
			<td>100.00元</td>
		  </tr>
		  <tr>
			<td>038</td>
			<td>粪常规</td>
			<td>/次</td>
			<td>5.00元</td>
		  </tr>
		  <tr>
			<td>039</td>
			<td>精浆果糖</td>
			<td>/次</td>
			<td>100.00元</td>
		  </tr>
		  <tr>
			<td>040</td>
			<td> 抗精子抗体</td>
			<td>/次</td>
			<td>50.00元</td>
		  </tr>
		  <tr>
			<td>041</td>
			<td> 抗HCG抗体</td>
			<td>/次</td>
			<td>80.00元</td>
		  </tr>
		  <tr>
			<td>042</td>
			<td> 前列腺特异抗原</td>
			<td>/次</td>
			<td>120.00元</td>
		  </tr>
		  <tr>
			<td>043</td>
			<td>涂片滴虫检查</td>
			<td>/次</td>
			<td>40.00元</td>
		  </tr>
		  <tr>
			<td>044</td>
			<td> 涂片霉菌检查</td>
			<td>/次</td>
			<td>40.00元</td>
		  </tr>
		</tbody></table>
	  </div>
      </div>
    </div>
  </div>
  
  